Lab 8/EsteCarII/EsteCarII/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using EsteCarII.Models;

namespace EsteCarII.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "EsteCar.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Contactos.";

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Lab 8/EsteCarII/EsteCarII/ViewComponents/AlugueresHojeViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using EsteCarII.Services;
using Microsoft.AspNetCore.Mvc;

namespace EsteCarII.ViewComponents
{
    public class AlugueresHojeViewComponent : ViewComponent
    {
        private IAlugueresHoje _alugueresHoje;

        public AlugueresHojeViewComponent(IAlugueresHoje alugueresHoje)
        {
            _alugueresHoje = alugueresHoje;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            return View(_alugueresHoje.AlgueresHoje);
        }
    }
}

Lab 8/EsteCarII/EsteCarII/Views/Home/About.cshtml
@{
    ViewData["Title"] = "Sobre Nós";
}
<h2>@ViewData["Title"]</h2>

<p>ESTe Carro</p>
<br/>

<div>
    @await Component.InvokeAsync("AlugueresHoje")
</div>

Lab 8/EsteCarII/EsteCarII/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contactos";
}
<h2>@ViewData["Title"]</h2>

Lab 8/EsteCarII/EsteCarII/Views/Home/Index.cshtml
@using EsteCarII.Services
@inject IAlugueresHoje AlugueresHoje

@{
    ViewData["Title"] = "Home Page";
}

<p>Alugamos Carros</p>

<h3> Só Hoje </h3>

<p>
    <b>@AlugueresHoje.AlgueresHoje.Count()</b> Carro(s) Alugado(s)!
</p>